name: My CD

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Package
        run: pipx run build
      - uses: actions/upload-artifact@v4
        with: 
          path: dist/*
  
  publish:
    needs: 
      - build
    runs-on: ubuntu-latest
    environment: 
      name: testpypi
      url: https://test.pypi.org/p/wintersession2024cicd
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with: 
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
